Repository hbarton2/cscd350-f24-AndTheyWereRoomates, pull requests merged in 2024-12, with the labels that each got.

#211 Updated Pattern Document/Loads with exact positions GUI
  patterns.md
  src/main/java/org/project/Controller/ClassNodeService.java
  src/main/java/org/project/Controller/DraggableMaker.java
  src/main/java/org/project/Controller/GraphicalUserInterfaceController.java
  src/main/java/org/project/Model/UMLClassNode.java
  src/main/resources/GUIGraphics.fxml
  src/main/resources/saves/test1.json
  src/main/resources/saves/testsave.json
Labels: 💔 Bugs-n-Bunny, 👷 In Progress, Works on my computer 😎🤣

#218 bug/fix
  .github/workflows/GitAction.yml
  pom.xml
  recycle_bin/backup/CommandLineInterfaceController.java
  recycle_bin/backup/GitAction.yml
  recycle_bin/no_longer_needed/CommandLineTerminal.java
  src/main/java/org/project/Controller/ClassNodeService.java
  src/main/java/org/project/Controller/CommandBridgeAdapter.java
  src/main/java/org/project/Controller/CommandLineInterfaceController.java
  src/main/java/org/project/Controller/GraphicalUserInterfaceController.java
  src/main/java/org/project/Model/CommandLogic.java
  src/main/java/org/project/Model/CommandRegistries.java
  src/main/java/org/project/View/CommandLineTerminal.java
  src/main/resources/CLICommands.json
  src/main/resources/saves/temp_save.json
  src/main/resources/style.css
  src/test/java/org/project/IntegrationTest/ClassNodeIntegrationTest.java
  src/test/java/org/project/IntegrationTest/CommandLogicIntegrationTest.java
  src/test/java/org/project/TestDrivenDevelopment/CommandParserPrintTest.java
  src/test/java/org/project/TestDrivenDevelopment/GUIViewRefractTDD.java
  src/test/java/org/project/UnitTest/CommandRegistriesUnitTest.java
  src/test/java/org/project/UnitTest/MementosCaretakerUnitTest.java
Labels: 🩹🤕 I need a Band-Aid, 🔥 Critical Fix, 🚨 High Priority, 🔍 Needs Review, 🛠 Needs Testing, 📚 Documentation Needed, ✅ Ready for Release, 😴 I need to 😴 zzz, Works on my computer 😎🤣

#224 Update README.md
  .idea/misc.xml
  README.md
  doc/images/GUIBreakdown.png
  doc/images/GUIBug_CannotConnectToSelfError.png
  doc/images/GUIBug_SoftLimitOnElements2.png
  doc/images/GUIBugs_SoftLimitOnElements.png
  doc/images/GUIClassBreakdown.png
  doc/images/GUIEditorWindow.png
  doc/images/GUIFieldDiagram.png
  doc/images/GUIMethodDiagram.png
  doc/images/GUIMiscEdit.png
  doc/images/GUIMiscFile.png
  doc/images/GUIParameterDiagram.png
  doc/images/GUIRelationshipDiagram.png
  doc/images/GUISelectedElements.png
  doc/images/GUI_UI_Breakdown.png
  recycle_bin/no_longer_needed/ClassUIBreakdown.png
  recycle_bin/no_longer_needed/DetailedGUIBreakdown.png
  recycle_bin/no_longer_needed/GUIClassDiagram.png
  recycle_bin/no_longer_needed/GUIExamplePicture_ClassSelected.png
  recycle_bin/no_longer_needed/GUIExamplePicture_FieldSelected.png
  recycle_bin/no_longer_needed/GUIFieldDiagram.png
  recycle_bin/no_longer_needed/GUIMethodDiagram.png
  recycle_bin/no_longer_needed/GUIParameterDiagram.png
  recycle_bin/no_longer_needed/GUIRelationshipDiagram.png
  recycle_bin/no_longer_needed/GUIbug.png
  recycle_bin/no_longer_needed/GUIbug_RelationshipDisplayBug.png
  recycle_bin/no_longer_needed/GUIbug_RelationshipDisplayBugRealization.png
  recycle_bin/no_longer_needed/GUIbug_RelationshipGraphicalIssues.png
  recycle_bin/no_longer_needed/GUIbug_ReplationshipsNotRemoving.png
  recycle_bin/no_longer_needed/GUIbug_classesOverlayingGUIIssue.PNG
  recycle_bin/no_longer_needed/GUIbug_saveNotOpeningFileExplorer.PNG
  recycle_bin/no_longer_needed/UMLEDITORwindow.png
  recycle_bin/trash/TECHNICAL_DOC.md
Labels: 🍟Small, 🔍 Needs Review, 🤓 Do It Yourself, 🥒It sure is Kosher

#228 FEATURE - Save between CLI and GUI
  src/main/java/org/project/Controller/CommandBridge.java
  src/main/java/org/project/Controller/CommandBridgeAdapter.java
  src/main/java/org/project/Controller/GraphicalUserInterfaceController.java
Labels: 🩹🤕 I need a Band-Aid, Large, 😴 I need to 😴 zzz, 👻Already FIXED🦊, 🤓 Do It Yourself, 💪 Stay Strong, 🧰 Tool Kit in Action, 💻IT was here, 🥒It sure is Kosher, 😭Bad Vibes😭

#227 Testing PR with new GitAction
  .github/workflows/GitAction.yml
  .idea/misc.xml
  README.md
  pom.xml
  src/test/java/org/project/UnitTest/CommandParserUnitTest.java
Labels: ❓Question, 🚨 High Priority, 📚 Documentation Needed, 🧰 Tool Kit in Action

#229 changes to README for CLI and Testing sections
  README.md
  doc/images/CLIAddClass.png
  doc/images/CLIAddField.png
  doc/images/CLIAddMethod.png
  doc/images/CLIAddRelationship.png
  doc/images/CLIHelpMenu.png
  doc/images/CLIListDetail.png
  doc/images/CLILoadFile.png
  doc/images/CLISaveFile.png
  doc/images/CodeCoverageReadme1.png
  doc/images/CodeCoverageReadme2.png
  doc/images/CodeCoverageReadme3.png
  doc/images/CodeCoverageReadme4.png
Labels: 📚 Documentation, 🔍 Needs Review, 👷‍♀️Quick Fix, 💪 Stay Strong

#231 Refactor/unit testing
  src/test/java/org/project/UnitTest/CommandParserUnitTest.java
Labels: 🍟Small, 🤓 Do It Yourself, 🧰 Tool Kit in Action, 😭Bad Vibes😭

#233 java doc for the project.
  src/main/java/org/project/Controller/AggregationArrow.java
  src/main/java/org/project/Controller/ArrowStrategy.java
  src/main/java/org/project/Controller/ComboBoxObserver.java
  src/main/java/org/project/Controller/CommandBridgeAdapter.java
  src/main/java/org/project/Controller/CommandLineInterfaceController.java
  src/main/java/org/project/Controller/CompositionArrow.java
  src/main/java/org/project/Controller/GeneralizationArrow.java
  src/main/java/org/project/Controller/ObservableClass.java
  src/main/java/org/project/Controller/ObserverInterface.java
  src/main/java/org/project/Controller/RealizationArrow.java
  src/main/java/org/project/Main.java
  src/main/java/org/project/Memento/Caretaker.java
  src/main/java/org/project/Memento/Memento.java
  src/main/java/org/project/Model/CommandInfo.java
  src/main/java/org/project/Model/UMLClassNode.java
  src/main/java/org/project/View/TextAreaOutputStream.java
Labels: 📚 Documentation

#236 Refactor/tests/code coverage
  DUMMY.json
  src/main/resources/saves/temp_save.json
  src/test/java/org/project/UnitTest/CommandParseFailureUnitTest.java
  src/test/java/org/project/UnitTest/CommandParserUnitTest.java
  src/test/resources/CLICommands.json
  src/test/resources/saves/temp_save.json
Labels: Works on my computer 😎🤣, 💪 Stay Strong, 🥒It sure is Kosher

#238 Updated readme file Completed some tests
  DUMMY.json
  README.md
  doc/images/Jar.png
  doc/images/Releases.png
  doc/images/kosherPNG.png
  looksKosherToMe.PNG
  patterns.md
  src/test/java/org/project/UnitTest/CommandParserUnitTest.java
Labels: 📚 Documentation

#245 Undo/Redo bug
  src/main/java/org/project/Controller/GraphicalUserInterfaceController.java
  src/main/java/org/project/Model/CommandLogic.java
Labels: 🩹🤕 I need a Band-Aid, Large, 😴 I need to 😴 zzz, 🤓 Do It Yourself, 💪 Stay Strong, 🥒It sure is Kosher, 😭Bad Vibes😭

#249 HOT FIX for Git Actions, addressing missing manifesto
  .github/workflows/GitAction.yml
  pom.xml
Labels: ☠️ Won't Fix, 🔥 Critical Fix, 📚 Documentation Needed, ✅ Ready for Release, 👷‍♀️Quick Fix, 🤓 Do It Yourself

#248 Code Coverage 89%
  src/main/resources/saves/BrokenSave.json
  src/main/resources/saves/DUMMY.json
  src/test/java/org/project/UnitTest/CommandParseFailureUnitTest.java
  src/test/java/org/project/UnitTest/CommandParserUnitTest.java
  temp-save.json
Labels: 💪 Stay Strong
