Repository hbarton2/cscd350-f24-AndTheyWereRoomates, pull requests merged in 2024-11, with the labels that each got.

#167 refract/project
  README.md
  recycle_bin/CommandParserBackup.java
  src/main/java/org/project/Controller/CommandParser.java
  src/main/java/org/project/Controller/CommandResult.java
  src/main/java/org/project/Model/CommandRegistry.java
  src/main/java/org/project/View/Terminal.java
  src/test/java/org/project/CommandParserPrintTest.java
Labels: 👷 In Progress

#175 Refactor/technical document
  README.md
  doc/images/GUIbug_classesOverlayingGUIIssue.PNG
  doc/images/GUIbug_saveNotOpeningFileExplorer.PNG
  recycle_bin/trash/TECHNICAL_DOC.md
Labels: 📚 Documentation, 🌱 Enhancement

#179 refract/storage/CommandLogic
  src/main/java/org/project/Model/CommandLogic.java
  src/main/java/org/project/Model/Storage.java
  src/main/java/org/project/Model/UMLClassNode.java
Labels: 🩹🤕 I need a Band-Aid, 😴 I need to 😴 zzz

#180 Save/load Fixed bugs for command logic
  src/main/java/org/project/Controller/ClassNodeService.java
  src/main/java/org/project/Model/CommandLogic.java
  src/main/java/org/project/Model/CommandRegistries.java
  src/main/resources/CLICommands.json
  src/main/resources/NodesClassStorage.json
Labels: 🩹🤕 I need a Band-Aid, 😴 I need to 😴 zzz

#182 Implemented memento design pattern
  src/main/java/org/project/Memento/Caretaker.java
  src/main/java/org/project/Memento/Memento.java
  src/main/java/org/project/Model/CommandLogic.java
  src/main/java/org/project/Model/CommandRegistries.java
  src/main/java/org/project/Model/Storage.java
  src/main/java/org/project/Model/UMLClassNode.java
Labels: 🩹🤕 I need a Band-Aid, 😴 I need to 😴 zzz

#206 Refactor/GUI
  src/main/java/org/project/Controller/AggregationArrow.java
  src/main/java/org/project/Controller/ArrowStrategy.java
  src/main/java/org/project/Controller/ComboBoxObserver.java
  src/main/java/org/project/Controller/CommandBridge.java
  src/main/java/org/project/Controller/CommandBridgeAdapter.java
  src/main/java/org/project/Controller/CompositionArrow.java
  src/main/java/org/project/Controller/DraggableMaker.java
  src/main/java/org/project/Controller/GUIViewController.java
  src/main/java/org/project/Controller/GeneralizationArrow.java
  src/main/java/org/project/Controller/ObservableClass.java
  src/main/java/org/project/Controller/ObserverInterface.java
  src/main/java/org/project/Controller/RealizationArrow.java
  src/main/java/org/project/Model/CommandLogic.java
  src/main/java/org/project/View/ClassBox.java
  src/main/java/org/project/View/ClassBoxFactory.java
  src/main/resources/Main.fxml
  src/test/java/org/project/UnitTest/CommandRegistriesUnitTest.java
  src/test/java/org/project/UnitTest/MementosCaretakerUnitTest.java
Labels: 🩹🤕 I need a Band-Aid, 😴 I need to 😴 zzz, Works on my computer 😎🤣
